export const PERMISSIONS = {
  // Leads
  LEADS_VIEW: 'leads.view',
  LEADS_CREATE: 'leads.create',
  LEADS_UPDATE: 'leads.update',
  LEADS_DELETE: 'leads.delete',
  LEADS_ASSIGN: 'leads.assign',
  LEADS_EXPORT: 'leads.export',
  LEADS_IMPORT: 'leads.import',
  LEADS_CONVERT: 'leads.convert',

  // Customers
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CUSTOMERS_DELETE: 'customers.delete',

  // Deals
  DEALS_VIEW: 'deals.view',
  DEALS_CREATE: 'deals.create',
  DEALS_UPDATE: 'deals.update',
  DEALS_DELETE: 'deals.delete',

  // Calls
  CALLS_MAKE: 'calls.make',
  CALLS_RECEIVE: 'calls.receive',
  CALLS_VIEW: 'calls.view',
  CALLS_RECORDINGS_PLAY: 'calls.recordings.play',

  // Follow-ups
  FOLLOWUPS_VIEW: 'followups.view',
  FOLLOWUPS_CREATE: 'followups.create',
  FOLLOWUPS_UPDATE: 'followups.update',

  // Properties / Site Visits / Bookings (Jamin)
  PROPERTIES_VIEW: 'properties.view',
  PROPERTIES_UPDATE: 'properties.update',
  SITE_VISITS_VIEW: 'site_visits.view',
  SITE_VISITS_CREATE: 'site_visits.create',
  BOOKINGS_VIEW: 'bookings.view',
  BOOKINGS_CREATE: 'bookings.create',

  // Investors / Consultations (GHL)
  INVESTORS_VIEW: 'investors.view',
  INVESTORS_CREATE: 'investors.create',
  CONSULTATIONS_VIEW: 'consultations.view',
  CONSULTATIONS_CREATE: 'consultations.create',
  OPPORTUNITIES_VIEW: 'opportunities.view',
  OPPORTUNITIES_CREATE: 'opportunities.create',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  // Admin & Settings
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',
  AUDIT_VIEW: 'audit.view',

  // Platform (Super Admin)
  PLATFORM_MANAGE_COMPANIES: 'platform.companies.manage',
  PLATFORM_MANAGE_PACKAGES: 'platform.packages.manage',
  PLATFORM_CALL_CONFIG: 'platform.call_config.manage',
} as const;

export const FEATURES = {
  // Core Sales
  LEADS: 'leads',
  CUSTOMERS: 'customers',
  DEALS: 'deals',
  FOLLOWUPS: 'followups',

  // Calling
  CALLS: 'calls',
  CALL_RECORDING: 'call-recording',
  CALL_TRANSCRIPTION: 'call-transcription',

  // Jamin Bazaar Operations
  PROPERTIES: 'properties',
  SITE_VISITS: 'site-visits',
  BOOKINGS: 'bookings',

  // GHL India Ventures
  INVESTORS: 'investors',
  CONSULTATIONS: 'consultations',
  INVESTMENT_OPPORTUNITIES: 'investment-opportunities',

  // Analytics & Admin
  REPORTS: 'reports',
  USERS: 'users',
  ROLES: 'roles',
  COMPANY_SETTINGS: 'company-settings',
  AUDIT_LOGS: 'audit-logs',
} as const;

export const SYSTEM_ROLES = {
  super_admin: {
    name: 'Super Admin',
    code: 'super_admin',
    permissions: Object.values(PERMISSIONS),
  },
  company_admin: {
    name: 'Company Admin',
    code: 'company_admin',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_DELETE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_IMPORT, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE, PERMISSIONS.CUSTOMERS_DELETE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE, PERMISSIONS.DEALS_DELETE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW, PERMISSIONS.CALLS_RECORDINGS_PLAY,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_UPDATE, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE, PERMISSIONS.ROLES_VIEW, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_UPDATE, PERMISSIONS.AUDIT_VIEW,
    ],
  },
  sales_manager: {
    name: 'Sales Manager',
    code: 'sales_manager',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW, PERMISSIONS.CALLS_RECORDINGS_PLAY,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_UPDATE, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.USERS_VIEW,
    ],
  },
  sales_executive: {
    name: 'Sales Executive',
    code: 'sales_executive',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW,
    ],
  },
};

export const PIPELINE_STAGES = {
  default: ['New', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'],
  ghl: ['Enquiry', 'Contacted', 'Consultation', 'Qualified Investor', 'Investment Opportunity', 'Converted'],
  jamin: ['Enquiry', 'Contacted', 'Interested', 'Site Visit', 'Plot Selected', 'Booking', 'Converted'],
};
